### ISSUE TITLE
demo里好像有点小bug

### ISSUE THREAD

**Issue by fromIRIS** [Lucifier129/Lucifier129.github.io#3]
demo里好像有点小bug，有两个圆圈按钮切换时图片好几张一起切换

**Comment by Lucifier129** [comment]
@fromIRIS 哪个demo呀？

**Comment by fromIRIS** [comment]
http://lucifier129.github.io/lab/slideshow-by-own-jquery.html  
点击原点之后 或moveover第二个demo的原点，切换就不正常了@Lucifier129

**Comment by Lucifier129** [comment]
@fromIRIS 点击圆点会出现好几张翻动的现象，这在实现上就决定了；只有自动播放或者下一帧、上一帧时，才是一张张过渡的。

这个幻灯片实现缺失有问题；有时圆点跟图片对应关系乱了，可能是定时器或者计数器没匹配好导致的；暂时没时间去改它了。

**Comment by fromIRIS** [comment]
嗯，，，，我先去自己写一个，再有空来看看
